// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20210704205135_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Location = "Washington",
                            Name = "Olympic National Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            Location = "Washington",
                            Name = "North Cascades National Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            Location = "Washington",
                            Name = "Mount Rainier National Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Location = "Washington",
                            Name = "Cape Disappointment State Park",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 5,
                            Location = "Washington",
                            Name = "Deception Pass State Park",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 6,
                            Location = "Oregon",
                            Name = "Crater Lake National Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 7,
                            Location = "Oregon",
                            Name = "Smith Rock State Park",
                            Type = "State"
                        },
                        new
                        {
                            ParkId = 8,
                            Location = "California",
                            Name = "Joshua Tree National Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 9,
                            Location = "California",
                            Name = "Sequoia National Park",
                            Type = "National"
                        },
                        new
                        {
                            ParkId = 10,
                            Location = "Oregon",
                            Name = "Milo McIver State Park",
                            Type = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
